### ISSUE TITLE
小白提问 文章的分类

### ISSUE THREAD

**Issue by supergitquery** [thinkerchan/hexo-theme-greyshade#1]
您好,我想用你的主题,但是我不会开启文章分类功能,说明文档中的 "设置layout: cate" 我不理解是什么意思,所以请求说明以下,谢谢

**Comment by thinkerchan** [comment]
根据命令：
```
hexo new page categories 
```
会得到如下 md文档
```
---
title: categories
date: 2020-07-05 15:59:28
layout: "cate" // 注意要手动增加这一行
comments: false
---
```

**Comment by thinkerchan** [comment]
issue里面回复你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"supergitquery"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 凌晨0:24
收件人:&nbsp;"thinkerchan/hexo-theme-greyshade"<hexo-theme-greyshade@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[thinkerchan/hexo-theme-greyshade] 小白提问 文章的分类 (#1)





 
您好,我想用你的主题,但是我不会开启文章分类功能,说明文档中的 "设置layout: cate" 我不理解是什么意思,所以请求说明以下,谢谢

**Comment by supergitquery** [comment]
文章的分类页面有了，但是页面只显示了分类，没有分类下面的文章，是有什么书写格式吗？还是需要什么配置

**Comment by Tanky-Zhang** [comment]
您好看到这个分类以后，我有点疑问就是，分类我设置以后我在我的md文件中是这样设置的：
![image](https://user-images.githubusercontent.com/48041180/90402834-9a051600-e0d2-11ea-828a-658e4bc71271.png)
但是在我的博客中点击分类却是这样展示的，请问是我哪里配置的不对嘛？
![image](https://user-images.githubusercontent.com/48041180/90402900-b99c3e80-e0d2-11ea-96b9-1356034401c7.png)

**Comment by thinkerchan** [comment]
> 您好看到这个分类以后，我有点疑问就是，分类我设置以后我在我的md文件中是这样设置的：
> ![image](https://user-images.githubusercontent.com/48041180/90402834-9a051600-e0d2-11ea-828a-658e4bc71271.png)
> 但是在我的博客中点击分类却是这样展示的，请问是我哪里配置的不对嘛？
> ![image](https://user-images.githubusercontent.com/48041180/90402900-b99c3e80-e0d2-11ea-96b9-1356034401c7.png)

这样试试
```
---
title: 标题
date: 2020-08-19 10:10:15
categories:
  - 源码
tags:
---
```

**Comment by thinkerchan** [comment]
对本主题文件夹做一次 git pull ,修复了分类的bug

**Comment by Tanky-Zhang** [comment]
> 对本主题文件夹做一次 git pull ,修复了分类的bug

你好，好像现在更加糟糕了，现在产生的效果是这样的
![Uploading image.png…]()

**Comment by Tanky-Zhang** [comment]
> 对本主题文件夹做一次 git pull ,修复了分类的bug

现在好像是更加糟糕了出现了这种情况：
![image](https://user-images.githubusercontent.com/48041180/93360592-6a366300-f876-11ea-903e-af39aa022b7f.png)

**Comment by thinkerchan** [comment]
文章头没有加类别的话，会认归到“默认分类” cate.ejs可以改个名字

**Comment by Tanky-Zhang** [comment]
> ，会认归到“默认分类” cate.ejs可以改个名字

![image](https://user-images.githubusercontent.com/48041180/93401109-fb77fa80-f8b3-11ea-9e1f-b599888679af.png)
我已经加上分类了但是没有展示

**Comment by thinkerchan** [comment]
在我这边没有这个问题哦， 你换这个写法试试
```
categories:
  - 源码
```
