### ISSUE TITLE
关于站内搜索存在的疑问

### ISSUE THREAD

**Issue by Tanky-Zhang** [thinkerchan/hexo-theme-greyshade#3]
您好，感觉您的hexo的主题挺好的，但是不知道怎么配置站内搜索，希望得到您的指点

**Comment by thinkerchan** [comment]
![image](https://user-images.githubusercontent.com/4480412/90351764-c8073d80-e073-11ea-9c26-c320bccbae02.png)

```
 $ hexo new page search
```
然后按上图处理即可

**Comment by Tanky-Zhang** [comment]
> hexo new page search
好的非常感谢您了，现在已经成功了
